import pandas as pd
from astropy import units as u
from astropy.coordinates import SkyCoord

# Green Bank Telescope (GBT) Catalog Format (Astrid)
# Name      RA(J2000)       DEC(J2000)      Velocity    RefFrame    Redshift
# J1613...  16:13:08.63     -51:34:47.6     0.0         LSRK        0.0

INPUT_FILE = "./data/processed/final/golden_improved.csv"
OUTPUT_FILE = "./data/processed/gbt_golden_targets.cat"


def main():
    print(f"Loading {INPUT_FILE}...")
    try:
        df = pd.read_csv(INPUT_FILE)
    except (FileNotFoundError, OSError, pd.errors.EmptyDataError) as e:
        print(f"Golden List not found: {e}")
        return

    print("Generating GBT Observing Catalog...")

    with open(OUTPUT_FILE, "w") as f:
        f.write("# TASNI Golden Targets - Radio Silence Verification\n")
        f.write("# Generated by TASNI Pipeline\n")
        f.write("# Format: NAME RA DEC VELOCITY COORD_MODE\n")
        f.write("# ----------------------------------------------------------------\n")

        for i, row in df.iterrows():
            # Format RA/DEC to hh:mm:ss
            c = SkyCoord(row["ra"], row["dec"], unit="deg")
            ra_str = c.ra.to_string(unit=u.hour, sep=":", precision=2, pad=True)
            dec_str = c.dec.to_string(unit=u.deg, sep=":", precision=2, pad=True, alwayssign=True)

            # Name: short designation
            name = row["designation"]

            # Write line
            # Velocity 0 (Unknown distance/galactic), LSRK frame default
            f.write(f"{name:<20} {ra_str} {dec_str}  0.0  LSRK\n")

    print(f"Saved {len(df)} targets to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
